# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "l"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bartek Bulat", "Krzystof Kosman"]
  s.date = "2012-08-16"
  s.description = "Bunch of generators for lazy programmers"
  s.email = "admin@1000i.pl"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Rakefile",
    "app/controllers/l/admins_controller.rb",
    "app/controllers/l/users_controller.rb",
    "app/controllers/lazy_programmer/galleries_controller.rb",
    "app/controllers/lazy_programmer/gallery_photos_controller.rb",
    "app/controllers/lazy_programmer/mobile/galleries_controller.rb",
    "app/controllers/lazy_programmer/mobile/news_controller.rb",
    "app/controllers/lazy_programmer/mobile/pages_controller.rb",
    "app/controllers/lazy_programmer/mobile_controller.rb",
    "app/controllers/lazy_programmer/news_controller.rb",
    "app/controllers/lazy_programmer/newsletter_mails_controller.rb",
    "app/controllers/lazy_programmer/pages_controller.rb",
    "app/controllers/lazy_programmer/searches_controller.rb",
    "app/models/lazy_programmer/gallery.rb",
    "app/models/lazy_programmer/gallery_photo.rb",
    "app/models/lazy_programmer/news.rb",
    "app/models/lazy_programmer/newsletter_mail.rb",
    "app/models/lazy_programmer/page.rb",
    "app/views/application/index.html.erb",
    "app/views/application/search.html.erb",
    "app/views/devise/confirmations/new.html.erb",
    "app/views/devise/mailer/confirmation_instructions.html.erb",
    "app/views/devise/mailer/reset_password_instructions.html.erb",
    "app/views/devise/mailer/unlock_instructions.html.erb",
    "app/views/devise/passwords/edit.html.erb",
    "app/views/devise/passwords/new.html.erb",
    "app/views/devise/registrations/edit.html.erb",
    "app/views/devise/registrations/new.html.erb",
    "app/views/devise/sessions/new.html.erb",
    "app/views/devise/shared/_links.erb",
    "app/views/devise/unlocks/new.html.erb",
    "app/views/l/admins/_form.html.erb",
    "app/views/l/admins/_submenu.erb",
    "app/views/l/admins/_tooltip.html.erb",
    "app/views/l/admins/partials/_content.erb",
    "app/views/l/admins/partials/_footer.erb",
    "app/views/l/admins/partials/_header.erb",
    "app/views/l/admins/show.erb",
    "app/views/l/layouts/admin.html.erb",
    "app/views/l/layouts/admin_login.html.erb",
    "app/views/l/layouts/mobile.html.erb",
    "app/views/l/layouts/standard.html.erb",
    "app/views/l/layouts/subpage.html.erb",
    "app/views/l/partials/_breadcrumbs.erb",
    "app/views/l/partials/_content.erb",
    "app/views/l/partials/_content_main.erb",
    "app/views/l/partials/_footer.erb",
    "app/views/l/partials/_head.erb",
    "app/views/l/partials/_header.erb",
    "app/views/l/partials/_info_box.erb",
    "app/views/l/partials/_newsletter_box.erb",
    "app/views/l/partials/_search.erb",
    "app/views/l/partials/_social.erb",
    "app/views/l/partials/_switcher.erb",
    "app/views/l/users/_form.html.erb",
    "app/views/l/users/_submenu.erb",
    "app/views/l/users/_tooltip.html.erb",
    "app/views/l/users/edit.html.erb",
    "app/views/l/users/index.html.erb",
    "app/views/l/users/new.html.erb",
    "app/views/l/users/show.html.erb",
    "app/views/lazy_programmer/galleries/_form.html.erb",
    "app/views/lazy_programmer/galleries/_gallery_item.html.erb",
    "app/views/lazy_programmer/galleries/_submenu.erb",
    "app/views/lazy_programmer/galleries/_tooltip.html.erb",
    "app/views/lazy_programmer/galleries/edit.html.erb",
    "app/views/lazy_programmer/galleries/index.html.erb",
    "app/views/lazy_programmer/galleries/list.html.erb",
    "app/views/lazy_programmer/galleries/new.html.erb",
    "app/views/lazy_programmer/galleries/show.html.erb",
    "app/views/lazy_programmer/gallery_photos/_show_photos.erb",
    "app/views/lazy_programmer/gallery_photos/create.rjs",
    "app/views/lazy_programmer/gallery_photos/destroy.rjs",
    "app/views/lazy_programmer/mobile/error401.html.erb",
    "app/views/lazy_programmer/mobile/error404.html.erb",
    "app/views/lazy_programmer/mobile/galleries/index.html.erb",
    "app/views/lazy_programmer/mobile/galleries/show.html.erb",
    "app/views/lazy_programmer/mobile/index.html.erb",
    "app/views/lazy_programmer/mobile/news/index.html.erb",
    "app/views/lazy_programmer/mobile/news/show.html.erb",
    "app/views/lazy_programmer/mobile/pages/index.html.erb",
    "app/views/lazy_programmer/mobile/pages/show.html.erb",
    "app/views/lazy_programmer/news/_edit_form.erb",
    "app/views/lazy_programmer/news/_form.html.erb",
    "app/views/lazy_programmer/news/_submenu.erb",
    "app/views/lazy_programmer/news/_tooltip.html.erb",
    "app/views/lazy_programmer/news/edit.html.erb",
    "app/views/lazy_programmer/news/index.html.erb",
    "app/views/lazy_programmer/news/list.html.erb",
    "app/views/lazy_programmer/news/new.html.erb",
    "app/views/lazy_programmer/news/show.html.erb",
    "app/views/lazy_programmer/newsletter_mails/_form.html.erb",
    "app/views/lazy_programmer/newsletter_mails/_submenu.erb",
    "app/views/lazy_programmer/newsletter_mails/_tooltip.html.erb",
    "app/views/lazy_programmer/newsletter_mails/index.html.erb",
    "app/views/lazy_programmer/newsletter_mails/send_mail.html.erb",
    "app/views/lazy_programmer/pages/_edit_form.erb",
    "app/views/lazy_programmer/pages/_form.html.erb",
    "app/views/lazy_programmer/pages/_page_item.html.erb",
    "app/views/lazy_programmer/pages/_submenu.erb",
    "app/views/lazy_programmer/pages/_tooltip.html.erb",
    "app/views/lazy_programmer/pages/edit.html.erb",
    "app/views/lazy_programmer/pages/hidden.rjs",
    "app/views/lazy_programmer/pages/index.html.erb",
    "app/views/lazy_programmer/pages/new.html.erb",
    "app/views/lazy_programmer/pages/show.html.erb",
    "app/views/lazy_programmer/searches/_results.html.erb",
    "app/views/lazy_programmer/searches/index.html.erb",
    "app/views/newsletter/confirmation.html.erb",
    "app/views/newsletter/send_mail.html.erb",
    "config/initializers/setup_mail.rb",
    "config/locales/admin/pl.yml",
    "config/locales/devise.en.yml",
    "config/locales/devise.pl.yml",
    "config/locales/en.yml",
    "lib/generators/l/l/l_generator.rb",
    "lib/generators/l/l/templates/application_controller.rb",
    "lib/generators/l/l/templates/application_helper.rb",
    "lib/generators/l/l/templates/pl.yml",
    "lib/generators/l/l/templates/roles.rb",
    "lib/generators/l/l/templates/roles_users.rb",
    "lib/generators/l/l/templates/routes.rb",
    "lib/generators/l/l/templates/user_model.rb",
    "lib/generators/l/l/templates/users.rb",
    "lib/generators/l/module/module_generator.rb",
    "lib/l.rb",
    "lib/l/rails.rb",
    "lib/l/rails/engine.rb",
    "lib/l/version.rb",
    "public/swfupload.swf",
    "vendor/assets/images/admin/1000ideas_creative_agency.png",
    "vendor/assets/images/admin/array_down.gif",
    "vendor/assets/images/admin/array_up.gif",
    "vendor/assets/images/admin/icons.png",
    "vendor/assets/images/admin/select-array.gif",
    "vendor/assets/images/admin/tooltip-arr.png",
    "vendor/assets/images/ajax-loader.gif",
    "vendor/assets/images/ajax-loader.png",
    "vendor/assets/images/ceebox/cee-close-btn.png",
    "vendor/assets/images/ceebox/cee-next-btn.gif",
    "vendor/assets/images/ceebox/cee-next-btn.png",
    "vendor/assets/images/ceebox/cee-prev-btn.gif",
    "vendor/assets/images/ceebox/cee-prev-btn.png",
    "vendor/assets/images/ceebox/loader.gif",
    "vendor/assets/images/icons-18-black.png",
    "vendor/assets/images/icons-18-white.png",
    "vendor/assets/images/icons-36-black.png",
    "vendor/assets/images/icons-36-white.png",
    "vendor/assets/images/swfupload_button.png",
    "vendor/assets/javascripts/admin/admin.js",
    "vendor/assets/javascripts/admin/custom-forms.js",
    "vendor/assets/javascripts/admin/form_tabs.js",
    "vendor/assets/javascripts/admins.js",
    "vendor/assets/javascripts/ceebox/humor.json",
    "vendor/assets/javascripts/ceebox/jquery.ceebox-min.js",
    "vendor/assets/javascripts/ceebox/jquery.color.js",
    "vendor/assets/javascripts/ceebox/jquery.easing.js",
    "vendor/assets/javascripts/ceebox/jquery.metadata.js",
    "vendor/assets/javascripts/ceebox/jquery.swfobject.js",
    "vendor/assets/javascripts/fileprogress.js",
    "vendor/assets/javascripts/handlers.js",
    "vendor/assets/javascripts/jquery.autocomplete.pack.js",
    "vendor/assets/javascripts/jquery.jgd.dropdown.js",
    "vendor/assets/javascripts/jquery.livequery.js",
    "vendor/assets/javascripts/jquery.mobile.js",
    "vendor/assets/javascripts/search.js",
    "vendor/assets/javascripts/swfobject.js",
    "vendor/assets/javascripts/swfupload.js",
    "vendor/assets/javascripts/swfupload.queue.js",
    "vendor/assets/javascripts/upload.js",
    "vendor/assets/stylesheets/admin/activities.css.scss",
    "vendor/assets/stylesheets/admin/admin.css.scss",
    "vendor/assets/stylesheets/admin/admin_login.css.scss",
    "vendor/assets/stylesheets/admin/layout.css.scss",
    "vendor/assets/stylesheets/admin/layout/custom-forms.css.scss",
    "vendor/assets/stylesheets/admin/layout/filter.css.scss",
    "vendor/assets/stylesheets/admin/layout/forms.css.scss",
    "vendor/assets/stylesheets/admin/layout/gallery_photos.css.scss",
    "vendor/assets/stylesheets/admin/layout/send_mail.css.scss",
    "vendor/assets/stylesheets/admin/layout/sort.css.scss",
    "vendor/assets/stylesheets/admin/layout/switcher.css.scss",
    "vendor/assets/stylesheets/admin/layout/tables.css.scss",
    "vendor/assets/stylesheets/admin/layout/tabs.css.scss",
    "vendor/assets/stylesheets/admin/style.css.scss",
    "vendor/assets/stylesheets/admins.css",
    "vendor/assets/stylesheets/ceebox.css",
    "vendor/assets/stylesheets/common.css",
    "vendor/assets/stylesheets/jquery.autocomplete.css",
    "vendor/assets/stylesheets/jquery.jgd.dropdown.css",
    "vendor/assets/stylesheets/jquery.mobile.css",
    "vendor/assets/stylesheets/jquery_ui/jquery.ui.core.css",
    "vendor/assets/stylesheets/jquery_ui/jquery.ui.dialog.css",
    "vendor/assets/stylesheets/jquery_ui/jquery.ui.tabs.css",
    "vendor/assets/stylesheets/jquery_ui/jquery.ui.theme.css",
    "vendor/assets/stylesheets/scaffold.css",
    "vendor/assets/stylesheets/style.css"
  ]
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Gem for lazy programmers"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

